export enum UserTypes {
  GET_CURRENT_USER = "GET_CURRENT_USER",
  USER_LOADING = "USER_LOADING",
  SET_DATA_USER_REDUCER = "SET_DATA_USER_REDUCER",
  GET_ALLOWED_APP_LIST = "GET_ALLOWED_APP_LIST",
}

export enum CommonTypes {
  SET_COMMON_REDUCER = "SET_COMMON_REDUCER",
}
